### ISSUE TITLE
🐞: not working

### ISSUE THREAD

**Issue by adnjoo** [adnjoo/fast-youtube-summary#26]
### description

not working in production

### repro steps
1. go to e.g. https://fast-youtube-summary.vercel.app/
2. put YT URL in (e.g. https://www.youtube.com/watch?v=lqWe6XnSmrQ&t=102s&pp=ygUMbWlhbWkgdHJhdmVs)
3. press Summarize

nothing happens - check chrome console

expected behavior - see summary

08.20.24 

<img width="300" alt="Screenshot 2024-08-20 at 12 37 30 PM" src="https://github.com/user-attachments/assets/8262af65-0d4d-453f-927f-6b020b3919fb">

**Comment by adnjoo** [comment]
issue was wrong `OPENAI_KEY` in Vercel env variables

**Comment by hapheus** [comment]
Unfortunately not yet. 
I will try to get the transcripts with the other library soon.
